### ISSUE TITLE
Add Automatic Swagger generation.

### ISSUE THREAD

**Issue by eznix86** [jcarlosroldan/oink#5]
example, we should have a /api/docs. For API documentation. It can use some kind of reflection to find information

**Comment by jcarlosroldan** [comment]
The problem with automated api docs generation is that it would force us to drop the current combined parameter validation-retrieval, as it it non-trivial to detect what the parameters are for a given call.

It could be possible for a docs/OpenAPI spec generation endpoint to read the endpoints file to search for parameter calls using regex or the AST, but there are too many ways this can fail.
